# Generated by Django 4.2.26 on 2025-12-22 02:06

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text="标准标签名 (e.g., 'warm')", max_length=50, verbose_name='Standard Name')),
                ('category', models.CharField(choices=[('visual_mood', 'Visual Mood'), ('shot_type', 'Shot Type')], db_index=True, max_length=50, verbose_name='Category')),
                ('synonyms', models.JSONField(blank=True, default=list, help_text="同义词列表 (e.g., ['cozy', 'sunny'])", verbose_name='Synonyms')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Tag Definition',
                'verbose_name_plural': 'Tag Definitions',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
