# Generated by Django 4.2.26 on 2025-12-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagdefinition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tagdefinition',
            name='label_en',
            field=models.CharField(blank=True, help_text="英文显示名 (e.g., 'Warm')", max_length=50, verbose_name='Label EN'),
        ),
        migrations.AddField(
            model_name='tagdefinition',
            name='label_zh',
            field=models.CharField(blank=True, help_text="中文显示名 (e.g., '温暖')", max_length=50, verbose_name='Label ZH'),
        ),
        migrations.AlterField(
            model_name='tagdefinition',
            name='name',
            field=models.CharField(db_index=True, help_text="系统唯一标识 (e.g., 'warm')", max_length=50, unique=True, verbose_name='Canonical Key'),
        ),
        migrations.AlterField(
            model_name='tagdefinition',
            name='synonyms',
            field=models.JSONField(blank=True, default=list, help_text="入口映射词表 (包含中英文变体, e.g., ['cozy', '温馨'])", verbose_name='Entry Mapping'),
        ),
    ]
