# Generated by Django 4.2.25 on 2025-11-03 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='EdgeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Instance ID')),
                ('api_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='API Key')),
                ('name', models.CharField(max_length=255, verbose_name='Instance Name')),
                ('status', django_choices_field.fields.TextChoicesField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10, verbose_name='Status')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Last Heartbeat')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_instances', to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Edge Instance',
                'verbose_name_plural': 'Edge Instances',
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
