# Generated by Django 4.2.26 on 2025-11-25 21:01

from django.db import migrations, models
import django_choices_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="edgeinstance",
            name="deployment_type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("WIN_DOCKER", "Windows Docker Desktop (Local/LAN)"),
                    ("LINUX_DOCKER", "Linux Docker"),
                    ("WORKSTATION", "All-in-One Workstation"),
                ],
                default="LINUX_DOCKER",
                help_text="Physical form factor or deployment environment.",
                max_length=12,
                verbose_name="Deployment Type",
            ),
        ),
        migrations.AddField(
            model_name="edgeinstance",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Hardware notes or other remarks.",
                verbose_name="Remarks",
            ),
        ),
        migrations.AddField(
            model_name="edgeinstance",
            name="software_version",
            field=models.CharField(
                blank=True,
                default="v1.0.0",
                max_length=50,
                verbose_name="Software Version",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="attribute",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("PERSONAL", "Personal"),
                    ("COMPANY", "Company"),
                    ("COMMUNITY", "Community"),
                ],
                default="COMPANY",
                help_text="The nature of the organization.",
                max_length=9,
                verbose_name="Attribute",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="business_status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("INTENTION", "Intention"),
                    ("SIGNED", "Signed"),
                    ("SUSPENDED", "Suspended"),
                    ("PARTNER", "Partner"),
                    ("INTERNAL", "Group Internal"),
                ],
                default="INTENTION",
                help_text="Current business relationship status.",
                max_length=9,
                verbose_name="Business Status",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Contact Email"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Contact Name"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Internal notes.",
                verbose_name="Description/Notes",
            ),
        ),
        migrations.AlterField(
            model_name="edgeinstance",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("ONLINE", "Online"),
                    ("OFFLINE", "Offline"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                default="OFFLINE",
                max_length=15,
                verbose_name="Status",
            ),
        ),
    ]
