# Generated by Django 4.2.26 on 2025-11-25 21:41

from django.db import migrations, models
import django_choices_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_edgeinstance_deployment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeinstance',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Business switch to enable/disable this instance.', verbose_name='Is Enabled'),
        ),
        migrations.AlterField(
            model_name='edgeinstance',
            name='deployment_type',
            field=django_choices_field.fields.TextChoicesField(choices=[('WIN_DOCKER', 'Windows Docker Desktop (Local/LAN)'), ('LINUX_DOCKER', 'Linux Docker'), ('WORKSTATION', 'All-in-One Workstation')], default='LINUX_DOCKER', max_length=12, verbose_name='Deployment Type'),
        ),
        migrations.AlterField(
            model_name='edgeinstance',
            name='description',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='edgeinstance',
            name='status',
            field=django_choices_field.fields.TextChoicesField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=15, verbose_name='Connection Status'),
        ),
    ]
