# Generated by Django 4.2.26 on 2025-11-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_edgeinstance_is_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact Position'),
        ),
    ]
