# Generated by Django 4.2.26 on 2025-11-23 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('task_type', django_choices_field.fields.TextChoicesField(choices=[('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus (Cloud)'), ('CHARACTER_METRICS', 'Character Metrics (Cloud)'), ('CHARACTER_IDENTIFIER', 'Character Identifier (Cloud)'), ('CHARACTER_PIPELINE', 'Character Analysis Pipeline (Cloud)'), ('GENERATE_NARRATION', 'Generate Narration (Cloud)'), ('GENERATE_DUBBING', 'Generate Dubbing (Cloud)'), ('GENERATE_EDITING_SCRIPT', 'Generate Editing Script (Cloud)'), ('RUN_DUBBING', 'Run Dubbing (Edge)'), ('RUN_SYNTHESIS', 'Run Synthesis (Edge)')], max_length=30, verbose_name='Task Type')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('result', models.JSONField(blank=True, default=dict, null=True, verbose_name='Result')),
                ('logs', models.TextField(blank=True, null=True, verbose_name='Logs')),
                ('assigned_edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organization.edgeinstance', verbose_name='Assigned Edge')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created'],
            },
        ),
    ]
