# Generated by Django 4.2.25 on 2025-10-19 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Instance ID')),
                ('api_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='API Key')),
                ('name', models.CharField(max_length=255, verbose_name='Instance Name')),
                ('status', django_choices_field.fields.TextChoicesField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10, verbose_name='Status')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Last Heartbeat')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_instances', to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Edge Instance',
                'verbose_name_plural': 'Edge Instances',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('task_type', django_choices_field.fields.TextChoicesField(choices=[('GENERATE_NARRATION', 'Generate Narration (Cloud)'), ('RUN_DUBBING', 'Run Dubbing (Edge)'), ('RUN_SYNTHESIS', 'Run Synthesis (Edge)')], max_length=30, verbose_name='Task Type')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('result', models.JSONField(blank=True, default=dict, null=True, verbose_name='Result')),
                ('logs', models.TextField(blank=True, null=True, verbose_name='Logs')),
                ('assigned_edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task_manager.edgeinstance', verbose_name='Assigned Edge')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created'],
            },
        ),
    ]
