# Generated by Django 4.2.25 on 2025-10-21 08:29

from django.db import migrations
import django_choices_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=django_choices_field.fields.TextChoicesField(choices=[('GENERATE_NARRATION', 'Generate Narration (Cloud)'), ('RUN_DUBBING', 'Run Dubbing (Edge)'), ('RUN_SYNTHESIS', 'Run Synthesis (Edge)'), ('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus (Cloud)')], max_length=30, verbose_name='Task Type'),
        ),
    ]
