# Generated by Django 4.2.26 on 2025-11-25 22:22

from django.db import migrations
import django_choices_field.fields
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=django_choices_field.fields.TextChoicesField(choices=[('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus'), ('CHARACTER_METRICS', 'Character Metrics'), ('CHARACTER_IDENTIFIER', 'Character Identifier'), ('CHARACTER_PIPELINE', 'Character Analysis Pipeline'), ('GENERATE_NARRATION', 'Generate Narration'), ('GENERATE_DUBBING', 'Generate Dubbing'), ('GENERATE_EDITING_SCRIPT', 'Generate Editing Script')], max_length=30, verbose_name='Task Type'),
        ),
    ]
