# Generated by Django 4.2.25 on 2025-11-03 12:46

from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_options_and_more'),
        ('task_manager', '0002_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_edge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organization.edgeinstance', verbose_name='Assigned Edge'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=django_choices_field.fields.TextChoicesField(choices=[('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus (Cloud)'), ('CHARACTER_METRICS', 'Character Metrics (Cloud)'), ('CHARACTER_IDENTIFIER', 'Character Identifier (Cloud)'), ('CHARACTER_PIPELINE', 'Character Analysis Pipeline (Cloud)'), ('GENERATE_NARRATION', 'Generate Narration (Cloud)'), ('GENERATE_EDITING_SCRIPT', 'Generate Editing Script (Cloud)'), ('RUN_DUBBING', 'Run Dubbing (Edge)'), ('RUN_SYNTHESIS', 'Run Synthesis (Edge)')], max_length=30, verbose_name='Task Type'),
        ),
        migrations.DeleteModel(
            name='EdgeInstance',
        ),
    ]
