# Generated by Django 4.2.26 on 2025-11-25 22:32

from django.db import migrations
import django_choices_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_status_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=django_choices_field.fields.TextChoicesField(choices=[('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus'), ('CHARACTER_IDENTIFIER', 'Character Identifier'), ('GENERATE_NARRATION', 'Generate Narration'), ('GENERATE_DUBBING', 'Generate Dubbing'), ('GENERATE_EDITING_SCRIPT', 'Generate Editing Script'), ('LOCALIZE_NARRATION', 'Localize Narration')], max_length=30, verbose_name='Task Type'),
        ),
    ]
