# Generated by Django 4.2.26 on 2025-11-11 07:39

from django.db import migrations
import django_choices_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_task_assigned_edge_alter_task_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=django_choices_field.fields.TextChoicesField(choices=[('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus (Cloud)'), ('CHARACTER_METRICS', 'Character Metrics (Cloud)'), ('CHARACTER_IDENTIFIER', 'Character Identifier (Cloud)'), ('CHARACTER_PIPELINE', 'Character Analysis Pipeline (Cloud)'), ('GENERATE_NARRATION', 'Generate Narration (Cloud)'), ('GENERATE_DUBBING', 'Generate Dubbing (Cloud)'), ('GENERATE_EDITING_SCRIPT', 'Generate Editing Script (Cloud)'), ('RUN_DUBBING', 'Run Dubbing (Edge)'), ('RUN_SYNTHESIS', 'Run Synthesis (Edge)')], max_length=30, verbose_name='Task Type'),
        ),
    ]
