# Generated by Django 4.2.26 on 2025-12-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_task_duration_task_finished_at_task_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus'), ('CHARACTER_IDENTIFIER', 'Character Identifier'), ('GENERATE_NARRATION', 'Generate Narration'), ('GENERATE_DUBBING', 'Generate Dubbing'), ('GENERATE_EDITING_SCRIPT', 'Generate Editing Script'), ('LOCALIZE_NARRATION', 'Localize Narration')], max_length=30, verbose_name='Task Type'),
        ),
    ]
