# Generated by Django 4.2.26 on 2025-12-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus'), ('CHARACTER_IDENTIFIER', 'Character Identifier'), ('GENERATE_NARRATION', 'Generate Narration'), ('GENERATE_DUBBING', 'Generate Dubbing'), ('GENERATE_EDITING_SCRIPT', 'Generate Editing Script'), ('LOCALIZE_NARRATION', 'Localize Narration'), ('visual_analysis', 'Visual Analysis & Refinement'), ('subtitle_context', 'Subtitle Context Analysis'), ('character_pre_annotator', 'Character Pre-Annotator'), ('scene_pre_annotator', 'Scene Pre-Annotator')], max_length=30, verbose_name='Task Type'),
        ),
    ]
