"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


import os
from pathlib import Path
from decouple import config
# 我们需要一个库来解析 DATABASE_URL
# 我们需要将 dj-database-url 添加到 requirements.txt
import dj_database_url
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 从 .env 文件中读取
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# 从 .env 文件中读取，并将其转换为布尔值
DEBUG = config('DEBUG', default=False, cast=bool)

# 从 .env 文件中读取，并将其转换为一个列表
# (在 .env 中，主机名用逗号分隔, 例如: ALLOWED_HOSTS=localhost,127.0.0.1)
# 我们在 .env 中设置了 '*' (星号)，用于开发
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=lambda v: [s.strip() for s in v.split(',')])

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost,http://127.0.0.1',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# 1. 确保 USE_I18N 为 True (Django 默认开启)
USE_I18N = True

# 2. 定义您希望支持的语言
# (示例：英语 和 简体中文)
from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('en', _('English')),
    ('zh-hans', _('Simplified Chinese')),
]


# Application definition

INSTALLED_APPS = [
    # Django Admin Theme (Unfold)
    'unfold',  # 必须在 'django.contrib.admin' 之前
    'unfold.contrib.filters',
    'unfold.contrib.forms',

    # Django Core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd Party Apps
    'rest_framework',
    'corsheaders',
    'django_fsm', # matching django-fsm-2
    'fsm_admin',
    'crispy_forms',
    'crispy_tailwind',
    'django_choices_field',
    'solo',

    # --- 在这里添加您的新 App ---
    'organization',
    'task_manager',
    'utils',
    'ai_services',
    # ---------------------------
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 4. 定义翻译文件的存储位置
# 我们将其设置在项目根目录的 'locale' 文件夹中
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# 使用 dj-database-url 从 .env 文件中解析 DATABASE_URL
DATABASE_URL = config('DATABASE_URL')
DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL)
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# UNFOLD THEME CONFIGURATION
# ==============================================================================
#
# 这是我们定义后台布局、侧边栏导航和标题的地方
#

UNFOLD = {
    "SITE_TITLE": _("Visify Story Studio (Cloud)"),
    "DASHBOARD_CALLBACK": "task_manager.dashboard.dashboard_callback",
    "SHOW_LANGUAGES": True,
    "SIDEBAR": {
        "navigation": [
            {
                "title": _("Account Management"),
                "items": [
                    {
                        "title": _("Organizations"),
                        # --- 修改这里 ---
                        # 从 "link": "admin:organization_organization_changelist"
                        # 改为直接的 URL 路径
                        "link": "/admin/organization/organization/",
                    },
                    # --- [修改] 暂时注释掉 User Profiles ---
                    # {
                    #     "title": _("User Profiles"),
                    #     "link": "/admin/organization/userprofile/",
                    # },
                    # -------------------------------------
{
                        "title": _("Edge Instances"),
                        "link": "/admin/organization/edgeinstance/",
                    },
                ],
            },
{
                "title": _("Task Management"),
                "items": [
                    {
                        "title": _("Tasks"),
                        "link": "/admin/task_manager/task/",
                    },

                ],
            },
            {
                "title": _("Authentication"),
                "items": [
                    {
                        "title": _("Users"),
                        # --- 修改这里 ---
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": _("Groups"),
                        # --- 修改这里 ---
                        "link": "/admin/auth/group/",
                    },
                ],
            },
        ]
    },
}

# CELERY CONFIGURATION
# 从 .env 文件中读取 REDIS_URL
CELERY_BROKER_URL = config('REDIS_URL')
CELERY_RESULT_BACKEND = config('REDIS_URL')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC' # 建议设置一个时区

# ==============================================================================
# CRISPY FORMS CONFIGURATION
# ==============================================================================
#
# 这是让 Unfold 主题能正确渲染所有 Admin 表单的关键配置
#
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Google Cloud Settings
GOOGLE_API_KEY = config('GOOGLE_API_KEY', default='')
GOOGLE_CLOUD_PROJECT = config('GOOGLE_CLOUD_PROJECT', default='')
GOOGLE_CLOUD_LOCATION = config('GOOGLE_CLOUD_LOCATION', default='')
GCS_DEFAULT_BUCKET = config('GCS_DEFAULT_BUCKET', default='')

# ==============================================================================
# Gemini API Pricing & Cost Calculation
# ==============================================================================
#
# 从 .env 文件中读取并结构化所有与AI模型相关的定价信息
#

# -- 汇率 --
USD_TO_RMB_EXCHANGE_RATE = config('USD_TO_RMB_EXCHANGE_RATE', cast=float, default=7.25)

# --- 模型定价表 (单位: 美元 / 每百万 tokens) ---
# [核心更新]: 移除所有 1.5 模型，统一使用 2.5 系列 Vertex AI 价格
GEMINI_PRICING = {
    # --- 1. Gemini 2.5 Pro (200K Tiers) ---
    "gemini-2.5-pro": {
        "threshold": config('GEMINI_2_5_PRO_THRESHOLD_TOKENS', cast=int, default=200000),
        "standard": {
            "input": config('GEMINI_2_5_PRO_INPUT_USD_STANDARD', cast=float, default=1.25),
            "output": config('GEMINI_2_5_PRO_OUTPUT_USD_STANDARD', cast=float, default=10.00),
        },
        "long": {
            "input": config('GEMINI_2_5_PRO_INPUT_USD_LONG', cast=float, default=2.50),
            "output": config('GEMINI_2_5_PRO_OUTPUT_USD_LONG', cast=float, default=15.00),
        }
    },

    # --- 2. Gemini 2.5 Flash (Flat Rate) ---
    "gemini-2.5-flash": {
        "threshold": config('GEMINI_2_5_FLASH_THRESHOLD_TOKENS', cast=int, default=9999999),  # Flat rate
        "standard": {
            "input": config('GEMINI_2_5_FLASH_INPUT_USD_STANDARD', cast=float, default=0.30),
            "output": config('GEMINI_2_5_FLASH_OUTPUT_USD_STANDARD', cast=float, default=2.50),
        },
        # NOTE: Flash 模型无长上下文分层，故不定义 'long' 键
    },

    # --- 3. Gemini 2.5 Flash-Lite (Flat Rate) ---
    "gemini-2.5-flash-lite": {
        "threshold": config('GEMINI_2_5_FLASH_LITE_THRESHOLD_TOKENS', cast=int, default=9999999),  # Flat rate
        "standard": {
            "input": config('GEMINI_2_5_FLASH_LITE_INPUT_USD_STANDARD', cast=float, default=0.10),
            "output": config('GEMINI_2_5_FLASH_LITE_OUTPUT_USD_STANDARD', cast=float, default=0.10),
        },
        # NOTE: Flash-Lite 模型无长上下文分层
    },
}


# --- [新增] 共享卷路径配置 ---
# 这个路径必须与 docker-compose.yml 中挂载的【容器内路径】完全一致
SHARED_ROOT = Path("/app/shared_media")

# [保留] 用于所有 API 交互（上传、过程文件、输出）
SHARED_TMP_ROOT = SHARED_ROOT / "tmp"

# [新增] 仅用于内部AI服务调试日志
SHARED_LOG_ROOT = SHARED_ROOT / "logs"

# 在 Django 启动时，确保这些目录存在，这能避免很多潜在的 "File Not Found" 错误
# 在 Django 启动时，确保这些目录存在
SHARED_TMP_ROOT.mkdir(parents=True, exist_ok=True)
SHARED_LOG_ROOT.mkdir(parents=True, exist_ok=True)

# ==============================================================================
# Aliyun PAI-EAS (CosyVoice)
# ==============================================================================
PAI_EAS_SERVICE_URL = config('PAI_EAS_SERVICE_URL', default='')
PAI_EAS_TOKEN = config('PAI_EAS_TOKEN', default='')